services:
  plato-builder:
    build:
      context: ./plato
      dockerfile: ../builder.Dockerfile
    image: local-plato:builder
    volumes:
      - ./dist:/usr/src/plato/dist
      - ./logs:/usr/src/plato/logs
    develop:
      watch:
        - action: sync+restart
          path: ./plato/crates/
          target: /usr/src/plato/crates/

  plato-emulator:
    build:
      context: ./plato
      dockerfile: ../emulator.Dockerfile
    image: local-plato:emulator
    devices:
      - /dev/dri/card0
    environment:
      - DISPLAY=unix${DISPLAY}
    network_mode: "host"
    volumes:
      - ~/.Xauthority:/root/.Xauthority
      - /etc/localtime:/etc/localtime:ro
      - ./logs:/usr/src/plato/logs
    develop:
      watch:
        - action: sync+restart
          path: ./plato/crates/
          target: /usr/src/plato/crates/
