services:
  plato-builder:
    build:
      context: ./plato
      dockerfile: ../gcc-linaro-builder.Dockerfile
    image: local-plato-gcc-linaro-builder
    volumes:
      - ./dist:/usr/src/plato/dist
